#!/bin/bash

if [ "$#" -ne 2 ]; then
    exit 1
fi

if [ ! -d "$1" ] || [ ! -d "$2" ]; then
    exit 1
fi

find "$1" -type f -exec bash -c 'cp "$0" "${1}/${0#"$1"/}"' {} "$2" \;

find "$2" -type f -exec bash -c 'mv "$0" "${0%/*}/$(basename "$0" | sed "s/^.*\///")"' {} \;
