#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Использование: $0 <входной_каталог> <выходной_каталог>"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "Входной каталог не существует."
    exit 1
fi

if [ ! -d "$2" ]; then
    echo "Выходной каталог не существует."
    exit 1
fi

function copy_files() {
    for element in "$1"/*; do
        if [ -d "$element" ]; then
            copy_files "$element"
        elif [ -f "$element" ]; then
            file_name=$(basename "$element")
            new_file_name="$file_name"
            counter=1
            while [ -f "$2/$new_file_name" ]; do
                new_file_name="${file_name%.*}_$counter.${file_name##*.}"
                counter=$((counter + 1))
            done

            cp "$element" "$2/$new_file_name"
        fi
    done
}

copy_files "$1" "$2"
