#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <source_directory> <target_directory>"
    exit 1
fi

src_dir="$1"
target_dir="$2"

mkdir -p "$target_dir"

find "$src_dir" -type f -exec bash -c '
    file="$1"
    target_file="$2/$(basename "$file")"

    if [ -e "$target_file" ]; then
        target_file="$2/copy_$(basename "$file")"
    fi

    cp "$file" "$target_file"
' -- {} "$target_dir" \;
